-- Idempotent schema + seed script. Safe to run on every app startup.

CREATE TABLE IF NOT EXISTS checklist_items (
  id      TEXT PRIMARY KEY,
  label   TEXT NOT NULL,
  checked BOOLEAN NOT NULL,
  source  TEXT NOT NULL CHECK (source IN ('Calendar', 'Email', 'Reminder', 'Manual', 'Voice'))
);

-- Allow voice-created to-dos (backend/python/voice/daemon.py) alongside the
-- original sources -- idempotent: safe to re-run even though it's a plain
-- DROP+ADD rather than an IF-NOT-EXISTS form (no such form exists for CHECK).
ALTER TABLE checklist_items DROP CONSTRAINT IF EXISTS checklist_items_source_check;
ALTER TABLE checklist_items ADD CONSTRAINT checklist_items_source_check
  CHECK (source IN ('Calendar', 'Email', 'Reminder', 'Manual', 'Voice'));

INSERT INTO checklist_items (id, label, checked, source) VALUES
  ('t1', 'Standup at 10am', TRUE, 'Calendar'),
  ('t2', 'Reply to JPMC email', TRUE, 'Email'),
  ('t3', 'Gym session at 6pm', FALSE, 'Reminder'),
  ('t4', 'Call dad about rentals', FALSE, 'Manual')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS emails (
  id      TEXT PRIMARY KEY,
  account TEXT NOT NULL CHECK (account IN ('Personal', 'Work')),
  sender  TEXT NOT NULL,
  unread  BOOLEAN NOT NULL,
  subject TEXT NOT NULL,
  preview TEXT NOT NULL,
  body    TEXT NOT NULL
);

-- Real Outlook data now populates this table via the Microsoft Graph sync
-- (backend/src/outlook/sync.ts) -- add the column it needs and discard the
-- old fake seed rows (their IDs never collide with real Graph message IDs).
ALTER TABLE emails ADD COLUMN IF NOT EXISTS received_at TIMESTAMPTZ;
DELETE FROM emails WHERE id IN ('e1', 'e2', 'e3', 'e4');

CREATE TABLE IF NOT EXISTS notifications (
  id         TEXT PRIMARY KEY,
  source     TEXT NOT NULL,
  message    TEXT NOT NULL,
  read       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Real notifications are now generated by backend rules (backend/src/notifications/rules.ts)
-- in response to actual events (new email, a Garmin metric drop, a missed reminder) --
-- discard the old fake seed rows and the free-text timestamp column they used.
ALTER TABLE notifications DROP COLUMN IF EXISTS timestamp;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS read BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
DELETE FROM notifications WHERE id IN ('n1', 'n2', 'n3', 'n4', 'n5');

CREATE TABLE IF NOT EXISTS favorite_places (
  id             TEXT PRIMARY KEY,
  name           TEXT NOT NULL,
  eta_minutes    INTEGER NOT NULL,
  distance_miles NUMERIC NOT NULL,
  traffic        TEXT NOT NULL
);

INSERT INTO favorite_places (id, name, eta_minutes, distance_miles, traffic) VALUES
  ('p1', 'JPMC office', 18, 3.2, 'light traffic'),
  ('p2', 'Gym', 6, 1.1, 'clear'),
  ('p3', 'Dad''s garage', 22, 5.4, 'moderate traffic')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS home_status (
  id               INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  time             TEXT NOT NULL,
  date             TEXT NOT NULL,
  weather          TEXT NOT NULL,
  listening_active BOOLEAN NOT NULL,
  listening_label  TEXT NOT NULL
);

-- The single hardcoded reminder banner moved to the real `reminders` table below.
ALTER TABLE home_status DROP COLUMN IF EXISTS leave_banner_message;
ALTER TABLE home_status DROP COLUMN IF EXISTS leave_banner_action_label;

-- Holds a summary of what the voice daemon (backend/python/voice/daemon.py)
-- just captured (e.g. "Reminding Call mom at 5:00 PM"), shown in the
-- VoiceAssistPopup before it closes. Null when idle/nothing to show.
ALTER TABLE home_status ADD COLUMN IF NOT EXISTS voice_result TEXT;

INSERT INTO home_status (
  id, time, date, weather, listening_active, listening_label
) VALUES (
  1, '7:42 AM', 'Monday, Sept 14', '68°F, clear', TRUE, 'Listening'
)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS reminders (
  id           TEXT PRIMARY KEY,
  label        TEXT NOT NULL,
  due_at       TIMESTAMPTZ NOT NULL,
  dismissed_at TIMESTAMPTZ,
  source       TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'voice')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO reminders (id, label, due_at, source) VALUES
  ('r1', 'Leave by 6:00 PM for the gym', (CURRENT_DATE + TIME '18:00')::timestamptz, 'manual')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS garmin_stats (
  id                   INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  body_battery_value   INTEGER NOT NULL,
  body_battery_caption TEXT NOT NULL,
  steps_value          INTEGER NOT NULL,
  steps_goal           INTEGER NOT NULL,
  resting_hr_value     INTEGER NOT NULL,
  resting_hr_caption   TEXT NOT NULL,
  sleep_total          TEXT NOT NULL,
  sleep_deep_caption   TEXT NOT NULL,
  stress_level         TEXT NOT NULL,
  stress_caption       TEXT NOT NULL
);

INSERT INTO garmin_stats (
  id, body_battery_value, body_battery_caption, steps_value, steps_goal,
  resting_hr_value, resting_hr_caption, sleep_total, sleep_deep_caption,
  stress_level, stress_caption
) VALUES (
  1, 48, 'Down from 62 this morning', 6240, 8000,
  62, 'Normal range', '7h 15m', 'Deep: 1h 40m',
  'Low', 'Avg today: 22'
)
ON CONFLICT (id) DO NOTHING;

-- Migrate an existing demo-shaped table (fixed Tue->Mon rotation) to real dates.
-- No-ops on a fresh DB (table/column don't exist yet) and on every run after
-- the first migration (day_label no longer exists). The old demo rows are
-- discarded -- real history only ever arrives via the Python Garmin sync now.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'garmin_weekly_stats' AND column_name = 'day_label'
  ) THEN
    ALTER TABLE garmin_weekly_stats DROP COLUMN day_label;
    ALTER TABLE garmin_weekly_stats DROP COLUMN day_index;
    ALTER TABLE garmin_weekly_stats ADD COLUMN date DATE;
    DELETE FROM garmin_weekly_stats WHERE date IS NULL;
    ALTER TABLE garmin_weekly_stats ALTER COLUMN date SET NOT NULL;
    ALTER TABLE garmin_weekly_stats ADD CONSTRAINT garmin_weekly_stats_metric_date_key UNIQUE (metric, date);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS garmin_weekly_stats (
  id     SERIAL PRIMARY KEY,
  metric TEXT NOT NULL CHECK (metric IN ('bodyBattery', 'steps', 'restingHr', 'sleep', 'stress')),
  date   DATE NOT NULL,
  value  NUMERIC NOT NULL,
  UNIQUE (metric, date)
);
